# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/jeongmin/yocto/work/poky/meta \
  /home/jeongmin/yocto/work/poky/meta-poky \
  /home/jeongmin/yocto/work/poky/meta-yocto-bsp \
  /home/jeongmin/yocto/work/meta-openembedded/meta-oe \
  /home/jeongmin/yocto/work/meta-openembedded/meta-python \
  /home/jeongmin/yocto/work/meta-openembedded/meta-networking \
  /home/jeongmin/yocto/work/meta-raspberrypi \
  /home/jeongmin/yocto/work/meta-qt6 \
  /home/jeongmin/yocto/work/meta-custom/meta-env \
  /home/jeongmin/yocto/work/meta-custom/meta-app \
  /home/jeongmin/yocto/work/meta-custom/meta-piracer \
  /home/jeongmin/yocto/work/build-des/workspace \
  "
